import "./globals.scss";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={("flex min-h-screen flex-col items-center justify-between p-24")}>
        {children}
      </body>
    </html>
  );
}
